### ISSUE TITLE
Combination of lint + test coverage report throws

### ISSUE THREAD

**Issue by nkbt** [keithamus/parallelshell#36]
I see it pretty awkward. Same issue for `concurrently`

```
21:03 $ `npm bin`/parallelshell '`npm bin`/eslint .' '`npm bin`/karma start ./karma.conf.js --single-run --reporters coverage' -w

fs.js:691
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/nkbt/nkbt/react-component-template/reports/coverage/prettify.js'
    at Object.fs.lstatSync (fs.js:691:18)
    at Object.realpathSync (fs.js:1279:21)
    at executeOnFile (/Users/nkbt/nkbt/react-component-template/node_modules/eslint/lib/cli-engine.js:559:27)
    at Array.forEach (native)
    at /Users/nkbt/nkbt/react-component-template/node_modules/eslint/lib/cli-engine.js:626:49
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/Users/nkbt/nkbt/react-component-template/node_modules/eslint/lib/cli-engine.js:622:18)
    at Object.cli.execute (/Users/nkbt/nkbt/react-component-template/node_modules/eslint/lib/cli.js:159:95)
    at Object.<anonymous> (/Users/nkbt/nkbt/react-component-template/node_modules/eslint/bin/eslint.js:61:20)
    at Module._compile (module.js:456:26)
Hash: c026f8c83672b2f634d8
Version: webpack 1.12.2
Time: 5ms
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
Hash: 95583aaf2ae88eb15123
Version: webpack 1.12.2
Time: 1284ms
        Asset    Size  Chunks             Chunk Names
test/index.js  675 kB       0  [emitted]  test/index.js
chunk    {0} test/index.js (test/index.js) 605 kB [rendered]
webpack: bundle is now VALID.
27 09 2015 21:03:32.066:INFO [karma]: Karma v0.13.10 server started at http://localhost:9876/
27 09 2015 21:03:32.070:INFO [launcher]: Starting browser PhantomJS
27 09 2015 21:03:32.917:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket lccv0AtAaeh84-jHAAAA with id 72480645
---------------|----------|----------|----------|----------|----------------|
File           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------|----------|----------|----------|----------|----------------|
 src/          |    88.89 |      100 |       50 |    66.67 |                |
  Component.js |    88.89 |      100 |       50 |    66.67 |              6 |
---------------|----------|----------|----------|----------|----------------|
All files      |    88.89 |      100 |       50 |    66.67 |                |
---------------|----------|----------|----------|----------|----------------|
```

Node 0.10.40

**Comment by keithamus** [comment]
@nkbt can you try using the parallelshell in #30 and see if that works any better for you?

**Comment by nkbt** [comment]
Checked out #30
```
[nkbt@nkbt] github $ git clone git@github.com:keithamus/parallelshell.git
Cloning into 'parallelshell'...
remote: Counting objects: 152, done.
remote: Total 152 (delta 0), reused 0 (delta 0), pack-reused 152
Receiving objects: 100% (152/152), 25.37 KiB | 0 bytes/s, done.
Resolving deltas: 100% (71/71), done.
Checking connectivity... done.
[nkbt@nkbt] github $ cd parallelshell/
✔ ~/github/parallelshell [master|✔] 
13:12 $ git fetch origin pull/30/head:dev
From github.com:keithamus/parallelshell
 * [new ref]         refs/pull/30/head -> dev
✔ ~/github/parallelshell [master|✔] 
13:12 $ git sw dev
Switched to branch 'dev'
```
Installed new pshell
```
[nkbt@nkbt] ~ $ cd nkbt/react-component-template/
✔ ~/nkbt/react-component-template [master|✔] 
13:13 $ git up
Fetching origin
master fast-forwarding...
✔ ~/nkbt/react-component-template [master|✔] 
13:13 $ npm install ~/github/parallelshell/
parallelshell@2.0.0 node_modules/parallelshell
```

Run. All good, but...

I doublechecked by running it again and it failed! Then again and it was ok. Then one more - failed: https://gist.github.com/nkbt/768cde05020c004659e4


Removed node-modules, made clean install. All is the same. Task every other time. 

When I add `-w` it seems to fail more consistently (like, every time) but exists with success code `0`

**Comment by keithamus** [comment]
I think your setup might be a red herring because parallelshell should not be affecting files and folders, the error you get is coming from eslint, not parallelshell:

```
fs.js:691
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/nkbt/nkbt/react-component-template/reports/coverage/prettify.js'
    at Object.fs.lstatSync (fs.js:691:18)
    at Object.realpathSync (fs.js:1279:21)
    at executeOnFile (/Users/nkbt/nkbt/react-component-template/node_modules/eslint/lib/cli-engine.js:559:27)
    at Array.forEach (native)
    at /Users/nkbt/nkbt/react-component-template/node_modules/eslint/lib/cli-engine.js:626:49
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/Users/nkbt/nkbt/react-component-template/node_modules/eslint/lib/cli-engine.js:622:18)
    at Object.cli.execute (/Users/nkbt/nkbt/react-component-template/node_modules/eslint/lib/cli.js:159:95)
    at Object.<anonymous> (/Users/nkbt/nkbt/react-component-template/node_modules/eslint/bin/eslint.js:61:20)
    at Module._compile (module.js:456:26)
```


Without `-w` the ouput is exactly what I'd expect - for whatever reason eslint is failing, and you get a non-zero exit code whenever that happens, and everything closes down. Certainly `-w` should still exit with non-zero; not sure why that's not happening though.
